name: old trigger

on:
  push:
    # 当 master 分支有变更的时候触发 workflow
    branches:
      - main
      - 'release-*'
      - 'test-*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Determine Branch
        id: branch-check
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      
      - name: Set Image Tag
        run: |
          if [[ $BRANCH == "main" ]]; then
            IMAGE_TAG="latest"
          elif [[ $BRANCH == "test" ]]; then
            IMAGE_TAG="test"
          elif [[ $BRANCH == "release-"* ]]; then
            IMAGE_TAG=${BRANCH#"release-"}
          else
            IMAGE_TAG="latest"
          fi
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo $IMAGE_TAG

      - name: Send repository dispatch event
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          OWNER: aroundabout
          REPO: action_demo
          IMAGE_TAG: ${{ env.IMAGE_TAG }}

        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$OWNER/$REPO/dispatches \
            -d '{"event_type":"special_repository","client_payload":{"version":"'"$IMAGE_TAG"'"}}'
